CREATE CONSTRAINT ON (n:Character) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Faction) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Quest) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Item) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Region) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Dungeon) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Event) ASSERT n.id IS UNIQUE;
CREATE CONSTRAINT ON (n:Requirement) ASSERT n.id IS UNIQUE;

